apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: elma365-dbs
  namespace: elma365-dbs
spec:
  interval: 5m
  chart:
    spec:
      chart: elma365-dbs
      sourceRef:
        kind: HelmRepository
        name: elma365
        namespace: flux-system
  valuesFiles:
    - /values/values-elma365-dbs.yaml
